run:
  tests: true
  timeout: 10m
  sort-results: true
  allow-parallel-runners: true
  concurrency: 4

linters:
  disable-all: true
  enable:
    - dogsled
    - exportloopref
    - goconst
    - gocritic
    - gofumpt
    - gci
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nolintlint
    - staticcheck
    - revive
    - stylecheck
    - typecheck
    - unconvert
    - unused

issues:
  exclude-rules:
    - text: 'leading space'
      linters:
        - nolintlint

  max-issues-per-linter: 10000
  max-same-issues: 10000

linters-settings:
  gci:
    sections:
      - standard # Standard section: captures all standard packages.
      - default # Default section: contains all imports that could not be matched to another section type.
      - blank # blank imports
      - dot # dot imports
      - prefix(github.com/cometbft/cometbft)
      - prefix(cosmossdk.io)
      - prefix(github.com/cosmos/cosmos-sdk)
      - prefix(github.com/classic-terra/core)
    custom-order: true
  dogsled:
    max-blank-identifiers: 3
  nolintlint:
    allow-unused: false
    allow-leading-space: true
    require-explanation: false
    require-specific: false
