defaults:
  actions:
    backport:
      assignees:
        - "{{ author }}"

queue_rules:
  - name: default
    conditions:
      - "#approved-reviews-by>1"
    commit_message_template: |
      {{ title }} (#{{ number }})
      {{ body }}

pull_request_rules:
  - name: Automatic merge on approval to the main branch
    conditions:
      - "#approved-reviews-by>=1"
      - base=main
      - label=A:automerge
    actions:
      queue:
        name: default
        method: squash
  - name: Backport patches to release/v3.1.x branch
    conditions:
      - base=main
      - label=backport/v3.1.x
    actions:
      backport:
        branches:
          - release/v3.1.x