version: '3.8'

services:
   core:     
     image: classic-terra/core
     build: 
      context: .
      dockerfile: Dockerfile
      labels:
        - "Contains the terrad binary"
   node:
     image: classic-terra/node
     build: 
       context: ./contrib/terra-operator
       dockerfile: Dockerfile      
       args:
         base_image: classic-terra/core
       labels:
        - "terraclassic.terrad-node.description=Contains everything to run a full node"