// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: terra/market/v1beta1/market.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the parameters for the market module.
type Params struct {
	BasePool           cosmossdk_io_math.LegacyDec `protobuf:"bytes,1,opt,name=base_pool,json=basePool,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"base_pool" yaml:"base_pool"`
	PoolRecoveryPeriod uint64                      `protobuf:"varint,2,opt,name=pool_recovery_period,json=poolRecoveryPeriod,proto3" json:"pool_recovery_period,omitempty" yaml:"pool_recovery_period"`
	MinStabilitySpread cosmossdk_io_math.LegacyDec `protobuf:"bytes,3,opt,name=min_stability_spread,json=minStabilitySpread,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"min_stability_spread" yaml:"min_stability_spread"`
	// Number of blocks per epoch for market burn/refill. Default: 30 days worth of blocks.
	EpochLengthBlocks uint64 `protobuf:"varint,4,opt,name=epoch_length_blocks,json=epochLengthBlocks,proto3" json:"epoch_length_blocks,omitempty" yaml:"epoch_length_blocks"`
	// Fraction of swap fee to burn [0,1]
	SwapFeeBurnRate cosmossdk_io_math.LegacyDec `protobuf:"bytes,5,opt,name=swap_fee_burn_rate,json=swapFeeBurnRate,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"swap_fee_burn_rate" yaml:"swap_fee_burn_rate"`
	// Fraction of swap fee to send to Community Pool [0,1]
	SwapFeeCommunityRate cosmossdk_io_math.LegacyDec `protobuf:"bytes,6,opt,name=swap_fee_community_rate,json=swapFeeCommunityRate,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"swap_fee_community_rate" yaml:"swap_fee_community_rate"`
	// Maximum age in seconds for oracle prices before swaps are denied. Default: 75 seconds (25 blocks * 3s)
	MaxOracleAgeSeconds uint64 `protobuf:"varint,7,opt,name=max_oracle_age_seconds,json=maxOracleAgeSeconds,proto3" json:"max_oracle_age_seconds,omitempty" yaml:"max_oracle_age_seconds"`
	// Number of blocks for TWAP calculation window. Default: 45 blocks
	TwapLookbackWindow uint64 `protobuf:"varint,8,opt,name=twap_lookback_window,json=twapLookbackWindow,proto3" json:"twap_lookback_window,omitempty" yaml:"twap_lookback_window"`
	// Maximum deviation from TWAP before swap is rejected [0,1]. Default: 0.10 (10%)
	MaxTwapDeviation cosmossdk_io_math.LegacyDec `protobuf:"bytes,9,opt,name=max_twap_deviation,json=maxTwapDeviation,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"max_twap_deviation" yaml:"max_twap_deviation"`
	// Daily cap factor: fraction of pool balance usable per day [0,1]. Default: 0.10 (10%)
	DailyCapFactor cosmossdk_io_math.LegacyDec `protobuf:"bytes,10,opt,name=daily_cap_factor,json=dailyCapFactor,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"daily_cap_factor" yaml:"daily_cap_factor"`
}

func (m *Params) Reset()      { *m = Params{} }
func (*Params) ProtoMessage() {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_114ea92c5ae3e66f, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetPoolRecoveryPeriod() uint64 {
	if m != nil {
		return m.PoolRecoveryPeriod
	}
	return 0
}

func (m *Params) GetEpochLengthBlocks() uint64 {
	if m != nil {
		return m.EpochLengthBlocks
	}
	return 0
}

func (m *Params) GetMaxOracleAgeSeconds() uint64 {
	if m != nil {
		return m.MaxOracleAgeSeconds
	}
	return 0
}

func (m *Params) GetTwapLookbackWindow() uint64 {
	if m != nil {
		return m.TwapLookbackWindow
	}
	return 0
}

func init() {
	proto.RegisterType((*Params)(nil), "terra.market.v1beta1.Params")
}

func init() { proto.RegisterFile("terra/market/v1beta1/market.proto", fileDescriptor_114ea92c5ae3e66f) }

var fileDescriptor_114ea92c5ae3e66f = []byte{
	// 628 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x94, 0xbf, 0x6e, 0xd4, 0x4a,
	0x14, 0xc6, 0xd7, 0xf7, 0xe6, 0xe6, 0x6e, 0x2c, 0x04, 0x61, 0xb2, 0x22, 0x4e, 0x22, 0xec, 0xc4,
	0x55, 0x9a, 0xac, 0x15, 0xa5, 0x4b, 0xc7, 0x26, 0x44, 0x42, 0x5a, 0x85, 0xc5, 0x8b, 0x40, 0xa2,
	0x19, 0x8d, 0xc7, 0x07, 0xaf, 0xb5, 0x1e, 0x8f, 0x35, 0x33, 0xfb, 0x4f, 0x50, 0x51, 0x52, 0x51,
	0x52, 0xe6, 0x21, 0x78, 0x88, 0xd0, 0x45, 0x54, 0x88, 0x62, 0x85, 0x92, 0x86, 0x7a, 0x9f, 0x00,
	0x79, 0xec, 0x8d, 0x84, 0xb3, 0xc5, 0x8a, 0xce, 0xfe, 0xfc, 0x3b, 0xdf, 0xf9, 0xce, 0xf1, 0x68,
	0xcc, 0x3d, 0x05, 0x42, 0x10, 0x8f, 0x11, 0xd1, 0x07, 0xe5, 0x0d, 0x0f, 0x03, 0x50, 0xe4, 0xb0,
	0x7c, 0x6d, 0x66, 0x82, 0x2b, 0x8e, 0x1a, 0x1a, 0x69, 0x96, 0x5a, 0x89, 0x6c, 0x6f, 0x51, 0x2e,
	0x19, 0x97, 0x58, 0x33, 0x5e, 0xf1, 0x52, 0x14, 0x6c, 0x37, 0x22, 0x1e, 0xf1, 0x42, 0xcf, 0x9f,
	0x0a, 0xd5, 0xfd, 0x5a, 0x37, 0x57, 0x3b, 0x44, 0x10, 0x26, 0x51, 0x60, 0xae, 0x05, 0x44, 0x02,
	0xce, 0x38, 0x4f, 0x2c, 0x63, 0xd7, 0xd8, 0xbf, 0xd7, 0x7a, 0x7a, 0x39, 0x75, 0x6a, 0x3f, 0xa6,
	0xce, 0x4e, 0xe1, 0x24, 0xc3, 0x7e, 0x33, 0xe6, 0x1e, 0x23, 0xaa, 0xd7, 0x6c, 0x43, 0x44, 0xe8,
	0xe4, 0x14, 0xe8, 0x6c, 0xea, 0xac, 0x4f, 0x08, 0x4b, 0x8e, 0xdd, 0xdb, 0x6a, 0xf7, 0xdb, 0x97,
	0x03, 0xb3, 0x6c, 0x7e, 0x0a, 0xd4, 0xaf, 0xe7, 0x5f, 0x3a, 0x9c, 0x27, 0xe8, 0x85, 0xd9, 0xc8,
	0x01, 0x2c, 0x80, 0xf2, 0x21, 0x88, 0x09, 0xce, 0x40, 0xc4, 0x3c, 0xb4, 0xfe, 0xd9, 0x35, 0xf6,
	0x57, 0x5a, 0xce, 0x6c, 0xea, 0xec, 0x14, 0x5e, 0x8b, 0x28, 0xd7, 0x47, 0xb9, 0xec, 0x97, 0x6a,
	0x47, 0x8b, 0xe8, 0x83, 0x61, 0x36, 0x58, 0x9c, 0x62, 0xa9, 0x48, 0x10, 0x27, 0xb1, 0x9a, 0x60,
	0x99, 0x09, 0x20, 0xa1, 0xf5, 0xaf, 0x1e, 0xa1, 0xb3, 0xdc, 0x08, 0x65, 0xdb, 0x45, 0x46, 0xd5,
	0x69, 0x10, 0x8b, 0xd3, 0xee, 0x9c, 0xe9, 0x6a, 0x04, 0x9d, 0x9b, 0x1b, 0x90, 0x71, 0xda, 0xc3,
	0x09, 0xa4, 0x91, 0xea, 0xe1, 0x20, 0xe1, 0xb4, 0x2f, 0xad, 0x15, 0x3d, 0x96, 0x3d, 0x9b, 0x3a,
	0xdb, 0x85, 0xff, 0x02, 0xc8, 0xf5, 0x1f, 0x6a, 0xb5, 0xad, 0xc5, 0x96, 0xd6, 0xd0, 0x3b, 0x13,
	0xc9, 0x11, 0xc9, 0xf0, 0x5b, 0x00, 0x1c, 0x0c, 0x44, 0x8a, 0x05, 0x51, 0x60, 0xfd, 0xa7, 0x27,
	0x3a, 0x5f, 0x6e, 0xa2, 0xad, 0xa2, 0xe3, 0x5d, 0x9b, 0xea, 0x3c, 0x0f, 0x72, 0xe4, 0x0c, 0xa0,
	0x35, 0x10, 0xa9, 0x4f, 0x14, 0xa0, 0x8f, 0x86, 0xb9, 0x79, 0x5b, 0x46, 0x39, 0x63, 0x83, 0x34,
	0xdf, 0x86, 0x8e, 0xb0, 0xaa, 0x23, 0x74, 0x97, 0x8b, 0x60, 0x57, 0x22, 0xfc, 0xe9, 0x55, 0xcd,
	0xd1, 0x28, 0x73, 0x9c, 0xcc, 0x29, 0x1d, 0xe6, 0x95, 0xf9, 0x88, 0x91, 0x31, 0xe6, 0x82, 0xd0,
	0x04, 0x30, 0x89, 0x00, 0x4b, 0xa0, 0x3c, 0x0d, 0xa5, 0xf5, 0xbf, 0x5e, 0xee, 0xde, 0x6c, 0xea,
	0x3c, 0x2e, 0x7f, 0xde, 0x42, 0xce, 0xf5, 0x37, 0x18, 0x19, 0x3f, 0xd7, 0xfa, 0x93, 0x08, 0xba,
	0x85, 0x9a, 0x9f, 0x44, 0x95, 0xe7, 0x4a, 0x38, 0xef, 0x07, 0x84, 0xf6, 0xf1, 0x28, 0x4e, 0x43,
	0x3e, 0xb2, 0xea, 0xd5, 0x93, 0xb8, 0x88, 0x72, 0x7d, 0x94, 0xcb, 0xed, 0x52, 0x7d, 0xad, 0x45,
	0xf4, 0xde, 0x44, 0x79, 0x04, 0x5d, 0x10, 0xc2, 0x30, 0x26, 0x2a, 0xe6, 0xa9, 0xb5, 0xf6, 0x17,
	0x3f, 0xed, 0xae, 0x4d, 0x75, 0x59, 0xeb, 0x8c, 0x8c, 0x5f, 0x8e, 0x48, 0x76, 0x3a, 0x07, 0xd0,
	0xd0, 0x5c, 0x0f, 0x49, 0x9c, 0x4c, 0x30, 0xcd, 0xb7, 0x4d, 0xa8, 0xe2, 0xc2, 0x32, 0x75, 0xef,
	0xf6, 0x72, 0xbd, 0x37, 0x8b, 0xde, 0x55, 0x93, 0x6a, 0xe7, 0xfb, 0x1a, 0x38, 0x21, 0xd9, 0x99,
	0xfe, 0x7c, 0x5c, 0xff, 0x7c, 0xe1, 0xd4, 0x7e, 0x5d, 0x38, 0x46, 0xeb, 0xd9, 0xe5, 0xb5, 0x6d,
	0x5c, 0x5d, 0xdb, 0xc6, 0xcf, 0x6b, 0xdb, 0xf8, 0x74, 0x63, 0xd7, 0xae, 0x6e, 0xec, 0xda, 0xf7,
	0x1b, 0xbb, 0xf6, 0xc6, 0x8b, 0x62, 0xd5, 0x1b, 0x04, 0x4d, 0xca, 0x99, 0x47, 0x13, 0x22, 0x65,
	0x4c, 0x0f, 0x8a, 0x2b, 0x8e, 0x72, 0x01, 0xde, 0xf0, 0xc8, 0x1b, 0xcf, 0x2f, 0x3b, 0x35, 0xc9,
	0x40, 0x06, 0xab, 0xfa, 0x76, 0x3a, 0xfa, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x7e, 0x4c, 0xe4, 0x1c,
	0x09, 0x05, 0x00, 0x00,
}

func (this *Params) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Params)
	if !ok {
		that2, ok := that.(Params)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.BasePool.Equal(that1.BasePool) {
		return false
	}
	if this.PoolRecoveryPeriod != that1.PoolRecoveryPeriod {
		return false
	}
	if !this.MinStabilitySpread.Equal(that1.MinStabilitySpread) {
		return false
	}
	if this.EpochLengthBlocks != that1.EpochLengthBlocks {
		return false
	}
	if !this.SwapFeeBurnRate.Equal(that1.SwapFeeBurnRate) {
		return false
	}
	if !this.SwapFeeCommunityRate.Equal(that1.SwapFeeCommunityRate) {
		return false
	}
	if this.MaxOracleAgeSeconds != that1.MaxOracleAgeSeconds {
		return false
	}
	if this.TwapLookbackWindow != that1.TwapLookbackWindow {
		return false
	}
	if !this.MaxTwapDeviation.Equal(that1.MaxTwapDeviation) {
		return false
	}
	if !this.DailyCapFactor.Equal(that1.DailyCapFactor) {
		return false
	}
	return true
}
func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.DailyCapFactor.Size()
		i -= size
		if _, err := m.DailyCapFactor.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintMarket(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x52
	{
		size := m.MaxTwapDeviation.Size()
		i -= size
		if _, err := m.MaxTwapDeviation.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintMarket(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x4a
	if m.TwapLookbackWindow != 0 {
		i = encodeVarintMarket(dAtA, i, uint64(m.TwapLookbackWindow))
		i--
		dAtA[i] = 0x40
	}
	if m.MaxOracleAgeSeconds != 0 {
		i = encodeVarintMarket(dAtA, i, uint64(m.MaxOracleAgeSeconds))
		i--
		dAtA[i] = 0x38
	}
	{
		size := m.SwapFeeCommunityRate.Size()
		i -= size
		if _, err := m.SwapFeeCommunityRate.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintMarket(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	{
		size := m.SwapFeeBurnRate.Size()
		i -= size
		if _, err := m.SwapFeeBurnRate.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintMarket(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	if m.EpochLengthBlocks != 0 {
		i = encodeVarintMarket(dAtA, i, uint64(m.EpochLengthBlocks))
		i--
		dAtA[i] = 0x20
	}
	{
		size := m.MinStabilitySpread.Size()
		i -= size
		if _, err := m.MinStabilitySpread.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintMarket(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if m.PoolRecoveryPeriod != 0 {
		i = encodeVarintMarket(dAtA, i, uint64(m.PoolRecoveryPeriod))
		i--
		dAtA[i] = 0x10
	}
	{
		size := m.BasePool.Size()
		i -= size
		if _, err := m.BasePool.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintMarket(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintMarket(dAtA []byte, offset int, v uint64) int {
	offset -= sovMarket(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.BasePool.Size()
	n += 1 + l + sovMarket(uint64(l))
	if m.PoolRecoveryPeriod != 0 {
		n += 1 + sovMarket(uint64(m.PoolRecoveryPeriod))
	}
	l = m.MinStabilitySpread.Size()
	n += 1 + l + sovMarket(uint64(l))
	if m.EpochLengthBlocks != 0 {
		n += 1 + sovMarket(uint64(m.EpochLengthBlocks))
	}
	l = m.SwapFeeBurnRate.Size()
	n += 1 + l + sovMarket(uint64(l))
	l = m.SwapFeeCommunityRate.Size()
	n += 1 + l + sovMarket(uint64(l))
	if m.MaxOracleAgeSeconds != 0 {
		n += 1 + sovMarket(uint64(m.MaxOracleAgeSeconds))
	}
	if m.TwapLookbackWindow != 0 {
		n += 1 + sovMarket(uint64(m.TwapLookbackWindow))
	}
	l = m.MaxTwapDeviation.Size()
	n += 1 + l + sovMarket(uint64(l))
	l = m.DailyCapFactor.Size()
	n += 1 + l + sovMarket(uint64(l))
	return n
}

func sovMarket(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozMarket(x uint64) (n int) {
	return sovMarket(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMarket
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BasePool", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMarket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMarket
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthMarket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.BasePool.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PoolRecoveryPeriod", wireType)
			}
			m.PoolRecoveryPeriod = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMarket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PoolRecoveryPeriod |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinStabilitySpread", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMarket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMarket
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthMarket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MinStabilitySpread.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EpochLengthBlocks", wireType)
			}
			m.EpochLengthBlocks = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMarket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EpochLengthBlocks |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SwapFeeBurnRate", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMarket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMarket
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthMarket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.SwapFeeBurnRate.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SwapFeeCommunityRate", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMarket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMarket
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthMarket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.SwapFeeCommunityRate.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxOracleAgeSeconds", wireType)
			}
			m.MaxOracleAgeSeconds = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMarket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxOracleAgeSeconds |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TwapLookbackWindow", wireType)
			}
			m.TwapLookbackWindow = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMarket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TwapLookbackWindow |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxTwapDeviation", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMarket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMarket
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthMarket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MaxTwapDeviation.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DailyCapFactor", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMarket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMarket
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthMarket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.DailyCapFactor.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMarket(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMarket
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipMarket(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowMarket
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMarket
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMarket
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthMarket
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupMarket
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthMarket
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthMarket        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowMarket          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupMarket = fmt.Errorf("proto: unexpected end of group")
)
