ARG GO_VERSION="1.22"
FROM golang:${GO_VERSION}-alpine3.18

RUN set -eux; apk add --no-cache ca-certificates build-base;

# make cosmovisor statically linked
RUN go install -ldflags '-w -s -linkmode=external -extldflags "-Wl,-z,muldefs -static"' -trimpath cosmossdk.io/tools/cosmovisor/cmd/cosmovisor@latest

ENTRYPOINT [ "/bin/sh" ]