name: Push Images
on:
  release:
    types: [published, created, edited]
  push:
    branches:
      - main
      - "release/*"
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+" # Push events to matching v*, i.e. v1.0, v20.15.10
      - "v[0-9]+.[0-9]+.[0-9]+-rc*" # Push events to matching v*, i.e. v1.0-rc1, v20.15.10-rc5

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Check out the repo
        uses: actions/checkout@master
        with:
          fetch-depth: 0
      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - 
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Parse tag
        id: tag
        run: |
          VERSION=$(echo ${{ github.ref_name }} | sed "s/v//")
          MAJOR_VERSION=$(echo $VERSION | cut -d '.' -f 1)
          MINOR_VERSION=$(echo $VERSION | cut -d '.' -f 2)
          PATCH_VERSION=$(echo $VERSION | cut -d '.' -f 3)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "MAJOR_VERSION=$MAJOR_VERSION" >> $GITHUB_ENV
          echo "MINOR_VERSION=$MINOR_VERSION" >> $GITHUB_ENV
          echo "PATCH_VERSION=$PATCH_VERSION" >> $GITHUB_ENV
      - 
        name: Build and push 
        id: build_push_image
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile
          context: .
          push: true
          platforms: linux/amd64
          tags: |
            ghcr.io/classic-terra/terraclassic.terrad-binary:${{ env.MAJOR_VERSION }}
            ghcr.io/classic-terra/terraclassic.terrad-binary:${{ env.MAJOR_VERSION }}.${{ env.MINOR_VERSION }}
            ghcr.io/classic-terra/terraclassic.terrad-binary:${{ env.MAJOR_VERSION }}.${{ env.MINOR_VERSION }}.${{ env.PATCH_VERSION }}

