name: Run End-To-End Tests

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - frag/foundation
permissions:
  contents: read
  packages: write
  
jobs:
  e2e:
    name: Tests
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
      -
        name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20.4'
      -
        name: Check out repository code
        uses: actions/checkout@v4
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build e2e image
        uses: docker/build-push-action@v3
        with:
          file: ./tests/e2e/e2e.Dockerfile
          context: .
          platforms: linux/amd64
          tags: terra:debug
          build-args: |
            BASE_IMG_TAG=debug
      -
        name: Testing
        run: make test-e2e