name: Build & Test
on:
  pull_request:
  push:
    branches:
      - main
      - master
      - "release/*"
jobs:
  cleanup-runs:
    runs-on: ubuntu-latest
    steps:
      - uses: rokroskar/workflow-run-cleanup-action@master
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    if: "!startsWith(github.ref, 'refs/tags/') && github.ref != 'refs/heads/main'"

  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3.5.0
        with:
          go-version: 1.19
      - uses: actions/checkout@v3
      - name: build
        run: |
          make build
      - name: test & coverage report creation
        run: |
          go test ./... -mod=readonly -timeout 12m -race -coverprofile=coverage.txt -covermode=atomic -tags='ledger test_ledger_mock'

  liveness-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3.5.0
        with:
          go-version: 1.19
      - name: start localnet
        run: |
          make clean localnet-start
      - name: test liveness
        run: |
          ./contrib/localnet_liveness.sh 100 5 50 localhost
